#!/bin/tcsh
#PBS -q cs6210
#PBS -l nodes=1:fourcore
#PBS -l walltime=00:20:00
#PBS -N mptreefin
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2

echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 2

echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 4

echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8

echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 8


echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
/nethome/rshetty7/mpi/tree_final 2
/nethome/rshetty7/mpi/tree_final 4
/nethome/rshetty7/mpi/tree_final 8
echo "------------END------------------"
