#!/bin/tcsh
#PBS -q cs6210
#PBS -l nodes=1:fourcore
#PBS -l walltime=00:20:00
#PBS -N mpbarrierfin
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2

echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 2

echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 4

echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8

echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 8


echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------------------------"
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
/nethome/rshetty7/mpi/barrier_sense 2
/nethome/rshetty7/mpi/barrier_sense 4
/nethome/rshetty7/mpi/barrier_sense 8
echo "------------END------------------"
