/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef webproxy_H
#define webproxy_H

#include <thrift/TDispatchProcessor.h>
#include "base_types.h"

namespace Rpc {

class webproxyIf {
 public:
  virtual ~webproxyIf() {}
  virtual int32_t ping() = 0;
  virtual void httpget(std::string& _return, const std::string& url) = 0;
};

class webproxyIfFactory {
 public:
  typedef webproxyIf Handler;

  virtual ~webproxyIfFactory() {}

  virtual webproxyIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(webproxyIf* /* handler */) = 0;
};

class webproxyIfSingletonFactory : virtual public webproxyIfFactory {
 public:
  webproxyIfSingletonFactory(const boost::shared_ptr<webproxyIf>& iface) : iface_(iface) {}
  virtual ~webproxyIfSingletonFactory() {}

  virtual webproxyIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(webproxyIf* /* handler */) {}

 protected:
  boost::shared_ptr<webproxyIf> iface_;
};

class webproxyNull : virtual public webproxyIf {
 public:
  virtual ~webproxyNull() {}
  int32_t ping() {
    int32_t _return = 0;
    return _return;
  }
  void httpget(std::string& /* _return */, const std::string& /* url */) {
    return;
  }
};


class webproxy_ping_args {
 public:

  webproxy_ping_args() {
  }

  virtual ~webproxy_ping_args() throw() {}


  bool operator == (const webproxy_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const webproxy_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const webproxy_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class webproxy_ping_pargs {
 public:


  virtual ~webproxy_ping_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _webproxy_ping_result__isset {
  _webproxy_ping_result__isset() : success(false) {}
  bool success;
} _webproxy_ping_result__isset;

class webproxy_ping_result {
 public:

  webproxy_ping_result() : success(0) {
  }

  virtual ~webproxy_ping_result() throw() {}

  int32_t success;

  _webproxy_ping_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const webproxy_ping_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const webproxy_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const webproxy_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _webproxy_ping_presult__isset {
  _webproxy_ping_presult__isset() : success(false) {}
  bool success;
} _webproxy_ping_presult__isset;

class webproxy_ping_presult {
 public:


  virtual ~webproxy_ping_presult() throw() {}

  int32_t* success;

  _webproxy_ping_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _webproxy_httpget_args__isset {
  _webproxy_httpget_args__isset() : url(false) {}
  bool url;
} _webproxy_httpget_args__isset;

class webproxy_httpget_args {
 public:

  webproxy_httpget_args() : url() {
  }

  virtual ~webproxy_httpget_args() throw() {}

  std::string url;

  _webproxy_httpget_args__isset __isset;

  void __set_url(const std::string& val) {
    url = val;
  }

  bool operator == (const webproxy_httpget_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const webproxy_httpget_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const webproxy_httpget_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class webproxy_httpget_pargs {
 public:


  virtual ~webproxy_httpget_pargs() throw() {}

  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _webproxy_httpget_result__isset {
  _webproxy_httpget_result__isset() : success(false) {}
  bool success;
} _webproxy_httpget_result__isset;

class webproxy_httpget_result {
 public:

  webproxy_httpget_result() : success() {
  }

  virtual ~webproxy_httpget_result() throw() {}

  std::string success;

  _webproxy_httpget_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const webproxy_httpget_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const webproxy_httpget_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const webproxy_httpget_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _webproxy_httpget_presult__isset {
  _webproxy_httpget_presult__isset() : success(false) {}
  bool success;
} _webproxy_httpget_presult__isset;

class webproxy_httpget_presult {
 public:


  virtual ~webproxy_httpget_presult() throw() {}

  std::string* success;

  _webproxy_httpget_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class webproxyClient : virtual public webproxyIf {
 public:
  webproxyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  webproxyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t ping();
  void send_ping();
  int32_t recv_ping();
  void httpget(std::string& _return, const std::string& url);
  void send_httpget(const std::string& url);
  void recv_httpget(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class webproxyProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<webproxyIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (webproxyProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_httpget(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  webproxyProcessor(boost::shared_ptr<webproxyIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &webproxyProcessor::process_ping;
    processMap_["httpget"] = &webproxyProcessor::process_httpget;
  }

  virtual ~webproxyProcessor() {}
};

class webproxyProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  webproxyProcessorFactory(const ::boost::shared_ptr< webproxyIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< webproxyIfFactory > handlerFactory_;
};

class webproxyMultiface : virtual public webproxyIf {
 public:
  webproxyMultiface(std::vector<boost::shared_ptr<webproxyIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~webproxyMultiface() {}
 protected:
  std::vector<boost::shared_ptr<webproxyIf> > ifaces_;
  webproxyMultiface() {}
  void add(boost::shared_ptr<webproxyIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    return ifaces_[i]->ping();
  }

  void httpget(std::string& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->httpget(_return, url);
    }
    ifaces_[i]->httpget(_return, url);
    return;
  }

};

} // namespace

#endif
