#!/bin/tcsh
#PBS -q cs6210
#PBS -l nodes=1:fourcore
#PBS -l walltime=00:20:00
#PBS -N mpbarrierfin
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2

echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 2

echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 4

echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8

echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 8


echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------------------------"
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
/nethome/rshetty7/mpi/tree_barrier 2
/nethome/rshetty7/mpi/tree_barrier 4
/nethome/rshetty7/mpi/tree_barrier 8
echo "------------END------------------"
